### ISSUE TITLE
Code for paper Neurologic A*esque Decoding?

### ISSUE THREAD

**Issue by NinaTian98369** [GloriaXimingLu/a_star_uncons#1]
Hello Gloria, is this repo the code for this paper: Neurologic A*esque Decoding: Constrained Text Generation with Lookahead Heuristics? If yes, do you plan to add readme or documentations soon? Thanks!

**Comment by GloriaXimingLu** [comment]
This is the private version of code for our development only. Will publicly release the documented code very soon.
